-- Databricks notebook source
CREATE SCHEMA IF NOT EXISTS household;

CREATE SCHEMA IF NOT EXISTS campaigns;

CREATE SCHEMA IF NOT EXISTS coupons;

CREATE SCHEMA IF NOT EXISTS products;

CREATE SCHEMA IF NOT EXISTS testing;