-- Databricks notebook source
DROP SCHEMA IF EXISTS campaigns CASCADE;

DROP SCHEMA IF EXISTS household CASCADE;

DROP SCHEMA IF EXISTS coupons CASCADE;

DROP SCHEMA IF EXISTS products CASCADE;

DROP SCHEMA IF EXISTS testing CASCADE;